@startuml Copropriete
hide footbox
footer Page %page%/%lastpage%
actor internaute
actor utilisateur
box utilisateurs
actor coproprietaire
actor syndic
actor tresorier
actor comptable
end box
database dbCopropriete
internaute -> dbCopropriete : creer compte utilisateur
utilisateur -> dbCopropriete : creer copropriete
dbCopropriete -> dbCopropriete : affecter role syndic
syndic -> dbCopropriete : creer les parties privees
syndic -> dbCopropriete : creer les proprietaires
syndic -> dbCopropriete : affecter les roles de gestion
newpage
dbCopropriete -> dbCopropriete : generer les cotisations\nmensuelles a encaisser
coproprietaire -> dbCopropriete : saisir les versements
comptable -> dbCopropriete : saisir les versements
dbCopropriete -> tresorier : versements a valider
tresorier -> dbCopropriete : valider les versements
dbCopropriete -> coproprietaire : versement valide
comptable -> dbCopropriete : saisir les decaissements
dbCopropriete -> tresorier : decaissements a valider
tresorier -> dbCopropriete : valider les decaissements
comptable -> dbCopropriete : saisir les factures
comptable -> dbCopropriete : saisir les cotisations\nexceptionnelles a encaisser
newpage
coproprietaire <-> dbCopropriete : consulter sa propre\nsituation
coproprietaire <-> dbCopropriete : consulter situation\ncopropriete
comptable -> dbCopropriete : cloturer un exercice
dbCopropriete -> dbCopropriete : calculer le resultat\nde l'exercice
comptable -> dbCopropriete : ouvrir un nouveau exercice
dbCopropriete -> dbCopropriete : reporter les soldes des\ncomptes du bilan
coproprietaire -> dbCopropriete : mettre en location
coproprietaire -> dbCopropriete : mettre en vente
internaute <- dbCopropriete : disponibles pour location/vente
@enduml