# Generated by Django 3.1.3 on 2020-11-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('President', 'president'), ('Adjoint', 'adjoint'), ('Comptable', 'comptable'), ('Tresorier', 'tresorier')], max_length=20)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('partiesPrivees', models.ManyToManyField(related_name='hist_proprietaires', to='syndic.PartiePrivee')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='copropriete',
            name='creePar',
        ),
        migrations.AddField(
            model_name='copropriete',
            name='gereePar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coproprietesGerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Coproprietaire',
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='coproprietes',
            field=models.ManyToManyField(related_name='hist_gestionnaires', to='syndic.Copropriete'),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestionnaires', to=settings.AUTH_USER_MODEL),
        ),
    ]
