# Generated by Django 3.1.3 on 2020-12-20 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('Bilan-actif', 'bilan-actif'), ('Bilan-passif', 'bilan-passif'), ('CPC-Charges', 'cpc-charges'), ('CPC-Revenus', 'cpc-revenus')], max_length=20)),
                ('libelle_compte', models.CharField(max_length=50)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('President', 'president'), ('Adjoint', 'adjoint'), ('Comptable', 'comptable'), ('Tresorier', 'tresorier')], max_length=20)),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('copropriete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parametres', serialize=False, to='syndic.copropriete')),
                ('exerciceOuvert', models.IntegerField()),
                ('cotisationMensuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('modifieePar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.FileField(upload_to='justifs/%Y/%m/%d/')),
                ('date_comptable', models.DateTimeField(default=django.utils.timezone.now)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('compte_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_credit', to='syndic.compte')),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_debit', to='syndic.compte')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='copropriete',
            unique_together={('copropriete', 'ville')},
        ),
        migrations.AlterUniqueTogether(
            name='partieprivee',
            unique_together={('copropriete', 'identifiant')},
        ),
        migrations.DeleteModel(
            name='Coproprietaire',
        ),
        migrations.AddField(
            model_name='transaction',
            name='copropriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='syndic.copropriete'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creePar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsCrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='valideePar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionsValidees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='partiesPrivees',
            field=models.ManyToManyField(related_name='hist_proprietaires', to='syndic.PartiePrivee'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='coproprietes',
            field=models.ManyToManyField(related_name='hist_gestionnaires', to='syndic.Copropriete'),
        ),
        migrations.AddField(
            model_name='gestionnaire',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compte',
            name='copropriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='syndic.copropriete'),
        ),
        migrations.RemoveField(
            model_name='copropriete',
            name='creePar',
        ),
        migrations.AlterUniqueTogether(
            name='compte',
            unique_together={('copropriete', 'type_compte', 'libelle_compte')},
        ),
    ]
