# Generated by Django 3.1.3 on 2020-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0003_remove_copropriete_gereepar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='dateFin',
            field=models.DateTimeField(null=True),
        ),
    ]
