# Generated by Django 3.1.3 on 2020-11-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0005_auto_20201114_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionnaire',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
