# Generated by Django 3.1.3 on 2020-11-14 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0006_auto_20201114_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('Bilan-actif', 'bilan-actif'), ('Bilan-passif', 'bilan-passif'), ('Charges', 'charges'), ('Revenus', 'revenus')], max_length=20)),
                ('libelle_compte', models.CharField(max_length=50)),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='syndic.copropriete')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.FileField(upload_to='justifs/%Y/%m/%d/')),
                ('creeLe', models.DateTimeField(auto_now_add=True)),
                ('modifieLe', models.DateTimeField(auto_now=True)),
                ('compte_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_credit', to='syndic.compte')),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_debit', to='syndic.compte')),
                ('copropriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='syndic.copropriete')),
                ('creePar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsCrees', to=settings.AUTH_USER_MODEL)),
                ('valideePar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsValidees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
