# Generated by Django 3.1.3 on 2020-11-15 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0007_compte_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_comptable',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='compte',
            unique_together={('copropriete', 'type_compte', 'libelle_compte')},
        ),
        migrations.AlterUniqueTogether(
            name='copropriete',
            unique_together={('copropriete', 'adresse', 'ville')},
        ),
        migrations.AlterUniqueTogether(
            name='partieprivee',
            unique_together={('copropriete', 'identifiant')},
        ),
    ]
