# Generated by Django 3.1.3 on 2020-12-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0008_auto_20201115_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionnaire',
            name='dateDebut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='dateDebut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valideePar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionsValidees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='copropriete',
            unique_together={('copropriete', 'ville')},
        ),
    ]
