# Generated by Django 3.1.3 on 2020-12-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0011_auto_20201204_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copropparametres',
            name='id',
        ),
        migrations.AlterField(
            model_name='copropparametres',
            name='copropriete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='syndic.copropriete'),
        ),
    ]
