# Generated by Django 3.1.3 on 2020-12-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0013_auto_20201205_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CopropParametres',
            new_name='Parametre',
        ),
    ]
