# Generated by Django 3.1.3 on 2020-12-05 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0014_auto_20201205_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_comptable',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 16, 47, 5, 962309, tzinfo=utc)),
        ),
    ]
