# Generated by Django 3.1.3 on 2020-12-05 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndic', '0015_auto_20201205_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_comptable',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
